# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voice.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1051, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(142, 16777215))
        self.widget_2.setStyleSheet("border-image: url(:/pic/images/bg4.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setStyleSheet("border-image: url(:/pic/images/bg7.jpg);")
        self.widget.setObjectName("widget")
        self.sendMsgLineEdit = QtWidgets.QLineEdit(self.widget)
        self.sendMsgLineEdit.setGeometry(QtCore.QRect(190, 350, 641, 21))
        self.sendMsgLineEdit.setStyleSheet("border-image: url(:/pic/images/bg8.jpg);")
        self.sendMsgLineEdit.setText("")
        self.sendMsgLineEdit.setObjectName("sendMsgLineEdit")
        self.chatTextEdit = QtWidgets.QTextEdit(self.widget)
        self.chatTextEdit.setGeometry(QtCore.QRect(190, 70, 641, 261))
        self.chatTextEdit.setStyleSheet("border-image: url(:/pic/images/bg8.jpg);")
        self.chatTextEdit.setObjectName("chatTextEdit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(110, 180, 51, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(120, 350, 51, 16))
        self.label_5.setObjectName("label_5")
        self.sendMsgLineEdit.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.chatTextEdit.raise_()
        self.gridLayout.addWidget(self.widget, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setMaximumSize(QtCore.QSize(16777215, 462))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_3.setStyleSheet("border-image: url(:/pic/images/bg4.jpg);")
        self.widget_3.setObjectName("widget_3")
        self.splitter_3 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_3.setGeometry(QtCore.QRect(20, 10, 93, 28))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.play_PushButton_3 = QtWidgets.QPushButton(self.splitter_3)
        self.play_PushButton_3.setObjectName("play_PushButton_3")
        self.splitter_4 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_4.setGeometry(QtCore.QRect(300, 20, 151, 21))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_3 = QtWidgets.QLabel(self.splitter_4)
        self.label_3.setObjectName("label_3")
        self.perComboBox = QtWidgets.QComboBox(self.splitter_4)
        self.perComboBox.setObjectName("perComboBox")
        self.perComboBox.addItem("")
        self.perComboBox.addItem("")
        self.perComboBox.addItem("")
        self.perComboBox.addItem("")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_2.setGeometry(QtCore.QRect(510, 20, 114, 22))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setObjectName("label")
        self.volHorizontalSlider = QtWidgets.QSlider(self.splitter_2)
        self.volHorizontalSlider.setMaximum(9)
        self.volHorizontalSlider.setProperty("value", 5)
        self.volHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volHorizontalSlider.setObjectName("volHorizontalSlider")
        self.splitter_5 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_5.setGeometry(QtCore.QRect(680, 20, 114, 22))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_4 = QtWidgets.QLabel(self.splitter_5)
        self.label_4.setObjectName("label_4")
        self.sdpHorizontalSlider_2 = QtWidgets.QSlider(self.splitter_5)
        self.sdpHorizontalSlider_2.setMaximum(9)
        self.sdpHorizontalSlider_2.setProperty("value", 5)
        self.sdpHorizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.sdpHorizontalSlider_2.setObjectName("sdpHorizontalSlider_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(880, 20, 123, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.pitHorizontalSlider_3 = QtWidgets.QSlider(self.layoutWidget1)
        self.pitHorizontalSlider_3.setMaximum(9)
        self.pitHorizontalSlider_3.setProperty("value", 5)
        self.pitHorizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.pitHorizontalSlider_3.setObjectName("pitHorizontalSlider_3")
        self.horizontalLayout.addWidget(self.pitHorizontalSlider_3)
        self.gridLayout.addWidget(self.widget_3, 3, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 26))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu_F.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "对话框"))
        self.label_5.setText(_translate("MainWindow", "输入框"))
        self.play_PushButton_3.setText(_translate("MainWindow", "录音"))
        self.label_3.setText(_translate("MainWindow", "音色"))
        self.perComboBox.setItemText(0, _translate("MainWindow", "普通女声"))
        self.perComboBox.setItemText(1, _translate("MainWindow", "普通男声"))
        self.perComboBox.setItemText(2, _translate("MainWindow", "武侠"))
        self.perComboBox.setItemText(3, _translate("MainWindow", "软萌"))
        self.label.setText(_translate("MainWindow", "音量"))
        self.label_4.setText(_translate("MainWindow", "语速"))
        self.label_6.setText(_translate("MainWindow", "音调"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))

import bg_rc
